#!/bin/bash
# GENERATED by tb-smith for fazyrv — single-hart SCI TB runner.
# Pass criterion: "TB PASS" on stdout.
set -euo pipefail

HERE=$(cd "$(dirname "$0")" && pwd)
REPO=$(cd "$HERE/../../.." && pwd)

# Pinned stable Verilator (bug 21: nightly DFG miscompiles cv32e40x).
# VERILATOR_PIN=/path overrides; VERILATOR_PIN= (empty) uses PATH's verilator.
VPIN="${VERILATOR_PIN-/mnt/fda14e36-49c8-4508-a4b0-f37189565cd9/tools/verilator-5.050}"
if [ -n "$VPIN" ] && [ -x "$VPIN/usr/bin/verilator" ]; then
  export PATH="$VPIN/usr/bin:$PATH" VERILATOR_ROOT="$VPIN/usr/share/verilator"
fi

cd "$REPO"
rm -rf "build/tb_fazyrv_sci_obj"
verilator --binary -j 0 --timescale 1ns/1ps --top-module tb_fazyrv_sci   --Mdir "build/tb_fazyrv_sci_obj" -o "Vtb_fazyrv_sci"   -Wno-fatal -Wno-WIDTH -Wno-UNUSEDSIGNAL -Wno-UNDRIVEN -Wno-UNUSEDPARAM   -Wno-DECLFILENAME -Wno-PINMISSING -Wno-CASEINCOMPLETE -Wno-WIDTHEXPAND   -Wno-WIDTHTRUNC -Wno-UNOPTFLAT -Wno-TIMESCALEMOD -Wno-LATCH -Wno-MULTIDRIVEN   -Wno-GENUNNAMED -Wno-SYMRSVDWORD -Wno-IMPLICIT -Wno-COMBDLY   hw/core-v-mini-mcu/include/obi_pkg.sv   tb/mosaic/tb_obi_mem.sv   hw/sci/fazyrv_sci.sv   -f "$HERE/deps.f"   "$HERE/tb_fazyrv_sci.sv"

"build/tb_fazyrv_sci_obj/Vtb_fazyrv_sci"
