"""Emit a complete hardening config: invariant template plus derived floorplan.

Phase 1 measured the split this module depends on. Of the keys in Block A's
signoff config, 33 were byte-identical in Block B's and carried over untouched
onto a design they were never tuned for. Five are design-specific:
``DESIGN_NAME``, ``CLOCK_PERIOD``, ``FP_SIZING``, ``DIE_AREA``, ``CORE_AREA``.

So the template is a real file with its comments intact -- those comments
record what each PDN and timing value cost to learn, and regenerating them
through a YAML dumper would throw that away -- and only the five derived keys
are appended. The output is concatenation, the same shape ``run_signoff.sh``
already uses to append the resolved file list, so the derived block is visibly
separate from the reviewed one.

``CLOCK_PERIOD`` is derived even though both hardened designs happen to use
100 ns: they agree because both chose 10 MHz, not because the value is a
property of the flow. Treating a coincidence as an invariant is how a template
acquires a value nobody can justify.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any, List, Optional, Tuple

from harness.physical.floorplan import (
    DEFAULT_MARGIN_UM,
    Floorplan,
    SocInput,
    clock_period_ns,
    derive_floorplan,
)

# Keys the template must NOT contain, because they are derived per design.
DERIVED_KEYS = ("DESIGN_NAME", "CLOCK_PERIOD", "FP_SIZING", "DIE_AREA", "CORE_AREA")

DEFAULT_TEMPLATE = "flow/librelane/signoff_template.yaml"

_MODULE_NAME = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


def _format_value(value: Any) -> str:
    if isinstance(value, list):
        return "[" + ", ".join(_format_value(v) for v in value) + "]"
    if isinstance(value, float):
        # Trim a trailing .0 so DIE_AREA reads as LibreLane writes it.
        return f"{value:g}"
    return str(value)


def render_derived_block(
    design_name: str,
    floorplan: Floorplan,
    clock_ns: Optional[float],
) -> str:
    """The appended block, annotated with where each number came from."""
    lines = [
        "",
        "# ── DERIVED PER DESIGN — do not hand-edit ──────────────────────────",
        "#",
        "# Generated by `oh-my-soc physical-intent harden` from the SoC config",
        "# and its objectives. Everything above this line is the shared",
        f"# template ({DEFAULT_TEMPLATE}) and applies to every design.",
        "#",
        f"# cell area   {floorplan.logic_um2:,.0f} um2 post-CTS [{floorplan.basis}]",
        f"#             {floorplan.reason}",
        f"# utilisation {floorplan.target_utilisation:.1%} target",
        f"#             core {floorplan.core_side_um:.1f} um square",
        f"# margin      {floorplan.margin_um:g} um per side for the power ring",
        f"# die         {floorplan.die_side_um:.1f} um square"
        f" = {floorplan.die_area_mm2:.4f} mm2",
    ]
    # Routability caveats belong in the artefact, not only on someone's
    # terminal: the config outlives the command that produced it.
    for warning in floorplan.warnings:
        lines.append(f"# routability {warning}")
    lines += [
        "",
        f"DESIGN_NAME: {design_name}",
    ]
    if clock_ns is not None:
        lines += [
            f"# {1000.0 / clock_ns:g} MHz, from soc.objectives.target_clock_mhz."
            " A request, not a result:",
            "# STA decides whether it was met.",
            f"CLOCK_PERIOD: {_format_value(clock_ns)}",
        ]
    for key, value in floorplan.as_librelane().items():
        lines.append(f"{key}: {_format_value(value)}")
    for reference in floorplan.references:
        lines.append(f"# calibration: {reference}")
    return "\n".join(lines) + "\n"


def generate_hardening_config(
    soc: SocInput,
    design_name: str,
    *,
    repo_root: Path,
    template: str = DEFAULT_TEMPLATE,
    target_utilisation: Optional[float] = None,
    margin_um: float = DEFAULT_MARGIN_UM,
    clock_period_override: Optional[float] = None,
) -> Tuple[Optional[str], List[str]]:
    """Render a complete hardening config. Returns ``(text, errors)``."""
    template_path = repo_root / template
    if not template_path.is_file():
        return None, [f"no hardening template at {template}"]
    text = template_path.read_text()

    # A template carrying a derived key would silently win or lose depending on
    # YAML merge order, so refuse rather than resolve it.
    present = [k for k in DERIVED_KEYS
               if any(line.startswith(f"{k}:") for line in text.splitlines())]
    if present:
        return None, [
            f"template {template} sets design-specific key(s) {present}; "
            "those are derived per design and must not be in the shared template"
        ]

    # DESIGN_NAME becomes a SystemVerilog module name, so it has to be a legal
    # identifier -- `isalnum()` is not that test: it accepts "3leading", which
    # a synthesiser rejects far downstream and unhelpfully.
    if not _MODULE_NAME.fullmatch(design_name or ""):
        return None, [
            f"design name {design_name!r} is not a valid module name: it must "
            "start with a letter or underscore and contain only letters, "
            "digits and underscores"
        ]

    floorplan, errors = derive_floorplan(
        soc, target_utilisation=target_utilisation, margin_um=margin_um)
    if floorplan is None:
        return None, errors

    clock_ns = clock_period_override
    if clock_ns is None:
        clock_ns = clock_period_ns(soc)
    if clock_ns is None:
        return None, [
            "no clock period: set soc.objectives.target_clock_mhz, or pass an "
            "explicit override. It is not defaulted, because a clock nobody "
            "chose is the kind of number that ends up in a datasheet"
        ]
    if clock_ns <= 0:
        return None, ["clock period must be greater than 0 ns"]

    return text + render_derived_block(design_name, floorplan, clock_ns), []


def wrapper_path_for(design_name: str) -> str:
    """Where the delivery wrapper for a design must live.

    LibreLane requires DESIGN_NAME to equal the top module name, and signoff
    waivers are scoped by design name, so the wrapper is per design and named
    after it. `run_signoff.sh` derives the same path from the same rule.
    """
    return f"flow/librelane/experimental/{design_name}.sv"
