// Auto-generated by LibreLane
module mosaic_block_b(
`ifdef USE_POWER_PINS
  inout VSS,
  inout VDD,
`endif
  input clk_i,
  input rst_ni,
  input boot_select_i,
  input execute_from_flash_i,
  output spi_flash_sck_o,
  output spi_flash_cs_o,
  inout[3:0] spi_flash_sd_io,
  input uart_rx_i,
  output uart_tx_o,
  output status_valid_o,
  output[6:0] status_o
);
endmodule
